# Important Notes:
# Every field you add must be added to buildSrc/src/main/kotlin/multiloader-common.gradle.kts expandProps map.

# Project
version=26.1.2.0
group=com.example.examplemod
java_version=25

# Common
mod_name=ExampleMod
mod_author=Jared
mod_id=examplemod
license=CC0-1.0
credits=
description=The description of your mod. \nAccepts multilines.
minecraft_version_range=[26.1.2, 26.2)

neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
